<%@ Page Title="" Language="C#" MasterPageFile="~/MasterPage.master" AutoEventWireup="true" CodeFile="UpdateData.aspx.cs" Inherits="UpdateData" %>

<asp:Content ID="Content1" ContentPlaceHolderID="head" Runat="Server">
<style type="text/css">
        .auto-style1 {
            width: 104px;
        }
        .auto-style2 {
            width: 104px;
            height: 47px;
        }
        .auto-style3 {
            height: 28px;
        }
        .auto-style4 {
            height: 29px;
        }
        .auto-style5 {
            height: 47px;
        }
        .auto-style6 {
            width: 104px;
            height: 38px;
        }
        .auto-style7 {
            height: 38px;
        }
    </style>
</asp:Content>
<asp:Content ID="Content2" ContentPlaceHolderID="ContentPlaceHolder1" Runat="Server">
    <div class="t1" style="height: 700px; width: 760px; opacity: 0.9; float: left; margin-left: 20px; margin-top: 15px;margin-bottom:10px">
     <div style="height: 40px; width: 312px; margin-left:240px";><h3>Manage DataBase</h3></div>
          <table class="t1" style="width:300px; margin-left:120px;">
          <tr>
                <td colspan="3" class="auto-style3">&nbsp;<asp:Label ID="Label1" runat="server" Text="TO Add Single Data:" ForeColor="#993399" Visible="true"></asp:Label>
                    <asp:Label ID="Lbl_err" runat="server" Text="Something went wrong" ForeColor="Red" Visible="false"></asp:Label>
                </td>
         </tr>
         <tr>
                <td class="auto-style3">&nbsp;Floor No:</td>
                <td class="auto-style4">&nbsp;Space No:</td>
            </tr>
            <tr>
                <td><asp:TextBox ID="Tbox_floNo" runat="server"></asp:TextBox></td>
                <td><asp:TextBox ID="Tbox_SpaceNo" runat="server"></asp:TextBox></td>
                <td style="padding-left:30px"><asp:Button ID="Add" runat="server" OnClick="Add_Click" Text="Add" Width="130px" /></td>

            </tr>
         </table>

        <table class="t1" style="margin-left:120px;margin-bottom:10px; width: 532px;">
          <tr>
                <td colspan="3" class="auto-style3">&nbsp;<asp:Label ID="Label2" runat="server" Text="TO Add Multiple Data:" ForeColor="#993399" Visible="true"></asp:Label>
                    <asp:Label ID="Label3" runat="server" Text="Something went wrong" ForeColor="Red" Visible="false"></asp:Label>
                </td>
         </tr>
         <tr>
                <td class="auto-style6">&nbsp;Floor No:</td>
             <td class="auto-style7"><asp:TextBox ID="TextBox1" runat="server"></asp:TextBox></td>
                
            </tr>
            <tr>
                <td class="auto-style1">&nbsp;Space No:</td>
                <td>From:<asp:TextBox ID="Tb_frm" runat="server" Width="141px"></asp:TextBox></td>
                <td>To:<asp:TextBox ID="Tb_to" runat="server"></asp:TextBox></td>
                </tr>
            <tr>
                <td class="auto-style2"></td>
                <td class="auto-style5"></td>
                <td class="auto-style5" style="padding-left:30px"><asp:Button ID="Add_mul" runat="server" OnClick="Add_mul_Click" Text="Add" Width="130px" /></td>

            </tr>
         </table>
        <div style=" margin-left:120px;margin-top:50px ">
                <asp:GridView ID="GridView1" runat="server" AutoGenerateColumns="False" AutoGenerateDeleteButton="True" AutoGenerateEditButton="True" CellPadding="15" DataSourceID="DataSource_grid" ForeColor="#333333" GridLines="None" AllowPaging="True" DataKeyNames="Id" Width="530px">
            <AlternatingRowStyle BackColor="White" />
            <Columns>
                <asp:BoundField DataField="Id" HeaderText="Id" InsertVisible="False" ReadOnly="True" SortExpression="Id" />
                <asp:BoundField DataField="Floor" HeaderText="Floor" SortExpression="Floor" />
                <asp:BoundField DataField="space" HeaderText="space" SortExpression="space" />
            </Columns>
            <EditRowStyle BackColor="#f1d9f4" />
            <FooterStyle BackColor="#be8fd1" Font-Bold="True" ForeColor="White" />
            <HeaderStyle BackColor="#be8fd1" Font-Bold="True" ForeColor="White" />
            <PagerStyle BackColor="#be8fd1" ForeColor="White" HorizontalAlign="Center" />
            <RowStyle BackColor="#f1d9f4" />
            <SelectedRowStyle BackColor="#f1d9f4" Font-Bold="True" ForeColor="#333333" />
            <SortedAscendingCellStyle BackColor="#F5F7FB" />
            <SortedAscendingHeaderStyle BackColor="#6D95E1" />
            <SortedDescendingCellStyle BackColor="#E9EBEF" />
            <SortedDescendingHeaderStyle BackColor="#4870BE" />
        </asp:GridView>
        <asp:SqlDataSource ID="DataSource_grid" runat="server" ConnectionString="<%$ ConnectionStrings:ParkSmartlyDBConnectionString %>" SelectCommand="SELECT [Floor], [space], [Id] FROM [ParkingInformation]"  UpdateCommand="Update [ParkingInformation] Set [Floor]=@Floor, [space]=@space where [Id]=@Id" DeleteCommand="Delete from [ParkingInformation] where [Id]=@Id"></asp:SqlDataSource>
            </div>
     </div>

</asp:Content>

